vars:
    docker_compose_url: curl -SL https://github.com/docker/compose/releases/download/v2.40.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
    docker_compose_path: /usr/local/bin/docker-compose
