version: "3"

networks:
  custom-network:
    driver: bridge

volumes:
  mysql-data:

services:
  tomcat-service:
    image: tomcat:9.0
    container_name: tomcat-server
    ports:
      - "8080:8080"
    volumes:
      - "/mnt/wars:/usr/local/tomcat/webapps"
    restart: always
    depends_on:
      - mysql-service
    networks:
      - custom-network

  mysql-service:
    build:
    context: ./docker-compose
    dockerfile: Dockerfile  # Optional if filename is 'Dockerfile'  
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test   #only this db has access
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      # this is where your init.sql will be automatically executed
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - custom-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
