---
- name: configure nodes in dev and qa env
  hosts: all
  user: velocity
  become: yes
  connection: ssh
  gather_facts: yes

  vars:
    docker_compose_url: curl -SL https://github.com/docker/compose/releases/download/v2.40.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
    docker_compose_path: /usr/local/bin/docker-compose

  tasks:
    - name: update packages
      yum:
        name: '*'
        state: latest

    - name: install git java
      yum:
        name:
          - git
          - java-17-amazon-corretto.x86_64
        statee: present

    - name: install docker
      yum: 
        name: docker
        state: present
      notify: start docker

    - name: add user to group docker
      user:
        name: velocity
        groups: docker
        append: yes
    
    - name: install docker-compose
      get_url:
        url: "{{ docker_compose_url }}"
        dest: "{{ docker_compose_path }}"
        mode: '0755'

    - name: verify docker installation
      shell:
        docker --version
        git --version
        java -version 
        docker-compose --version
      register: output

  handlers:
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes


